config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/bitcoin', to: 'static_pages#home'
  get '/btc', to: 'static_pages#home'
  get '/eth', to: 'static_pages#eth'
  get '/ethereum', to: 'static_pages#eth'
  get '/bch', to: 'static_pages#bch'
  get '/bitcoin-cash', to: 'static_pages#bch'
  get '/ltc', to: 'static_pages#ltc'
  get '/litecoin', to: 'static_pages#ltc'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

	require 'open-uri'

  def home
  	json_now = JSON.parse(open("https://api.coindesk.com/v1/bpi/currentprice.json").read)
  	@price_now = json_now['bpi']['USD']['rate'].delete(',').to_f
  	
  	@start_date = Date.today-1.year
  	end_date = @start_date + 1.day
  	
  	json_year_ago = JSON.parse(open("https://api.coindesk.com/v1/bpi/historical/close.json?start=#{@start_date}&end=#{end_date}").read)
  	@price_year_ago = json_year_ago['bpi'].first.last

  	@percentage_change = (((@price_now / @price_year_ago)-1)*100).round(1)
  end

  def eth
    @price_now = JSON.parse(open("https://min-api.cryptocompare.com/data/price?fsym=ETH&tsyms=USD").read)['USD']
    @start_date = Date.today - 1.year
    @time_year_ago = @start_date.to_time.to_i
    @price_year_ago = JSON.parse(open("https://min-api.cryptocompare.com/data/pricehistorical?fsym=ETH&tsyms=USD&ts=#{@time_year_ago}").read)['ETH']['USD']
    @percentage_change = (((@price_now / @price_year_ago)-1)*100).round(1)
  end

  def bch
    @price_now = JSON.parse(open("https://min-api.cryptocompare.com/data/price?fsym=BCH&tsyms=USD").read)['USD']
    @start_date = Date.today-1.year
    @time_year_ago = @start_date.to_time.to_i
    @price_year_ago = JSON.parse(open("https://min-api.cryptocompare.com/data/pricehistorical?fsym=BCH&tsyms=USD&ts=#{@time_year_ago}").read)['BCH']['USD']
    @percentage_change = (((@price_now / @price_year_ago)-1)*100).round(1)
  end

  def ltc
    @price_now = JSON.parse(open("https://min-api.cryptocompare.com/data/price?fsym=LTC&tsyms=USD").read)['USD']
    @start_date = Date.today-1.year
    @time_year_ago = @start_date.to_time.to_i
    @price_year_ago = JSON.parse(open("https://min-api.cryptocompare.com/data/pricehistorical?fsym=LTC&tsyms=USD&ts=#{@time_year_ago}").read)['LTC']['USD']
    @percentage_change = (((@price_now / @price_year_ago)-1)*100).round(1)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CryptoYearAgo</title>
    <%= render '/google_analytics' %>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'static_pages/header' %>
    <%= yield %>
    <%= render 'static_pages/footer' %>
  </body>
</html>

app/views/static_pages/_footer.html.erb
<div class="site-footer">
	<ul>
		<li>
			<%= link_to "If you're interested in buying crypto then Coinbase is the easiest place to start. (This is a referral link)", "https://www.coinbase.com/join/5329a2a01f2743d8c60005f2", target:"_blank" %> 
		</li>
		<li>
			<%= link_to "Site by Ben Kinnard", "http://www.twitter.com/captainkinnard", target: "_blank" %>
				
		</li>
	</ul>
</div>

app/views/static_pages/_header.html.erb
<div class="site-header">
	<ul>
		<li><h1><%= link_to 'Crypto Year Ago', root_path %></h1></li>
		<li><%= link_to 'Bitcoin', root_path %></li>
		<li><%= link_to 'Ethereum', eth_path %></li>
		<li><%= link_to 'Bitcoin Cash', bch_path %></li>
		<li><%= link_to 'Litecoin', ltc_path %></li>
	</ul>
</div>

app/views/static_pages/bch.html.erb
<div class="page-wrap">
	<h2>Today Bitcoin Cash is worth <%= number_to_currency(@price_now) %></h2>
	<h2>On <%= @start_date.strftime("%B %d, %Y") %>, it was worth <%= number_to_currency(@price_year_ago)%></h2>
	<h2>It is up <%= @percentage_change %>% in the last year!</h2>
</div>	

app/views/static_pages/eth.html.erb
<div class="page-wrap">
	<h2>Today Etherum is worth <%= number_to_currency(@price_now) %></h2>
	<h2>On <%= @start_date.strftime("%B %d, %Y") %>, it was worth <%= number_to_currency(@price_year_ago)%></h2>
	<h2>It is up <%= @percentage_change %>% in the last year!</h2>
</div>	

app/views/static_pages/home.html.erb
<div class="page-wrap">
	<h2>Today Bitcoin is worth <%= number_to_currency(@price_now) %></h2>
	<h2>On <%= @start_date.strftime("%B %d, %Y") %>, it was worth <%= number_to_currency(@price_year_ago)%></h2>
	<h2>It is up <%= @percentage_change %>% in the last year!</h2>

	<!-- <p>Bitcoin hasn't been this low since <%= Date.new(2017, 11, 14) %>, a <%= (Date.today - Date.new(2017, 11, 14)).to_i %> day low.</p> -->

</div>	

app/views/static_pages/ltc.html.erb
<div class="page-wrap">
	<h2>Today Litecoin is worth <%= number_to_currency(@price_now) %></h2>
	<h2>On <%= @start_date.strftime("%B %d, %Y") %>, it was worth <%= number_to_currency(@price_year_ago)%></h2>
	<h2>It is up <%= @percentage_change %>% in the last year!</h2>
</div>	